version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    container_name: yannic-bruegger-beiboot-server
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: yannic-bruegger-beiboot-client
